version: '3.8'
services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=dbadmin
      - POSTGRES_PASSWORD=gymb00st3rdb
      - POSTGRES_DB=gym_booster_db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5433:5433'
volumes:
  postgres:
